twig:
    default_path: '%kernel.project_dir%/templates'

###> Nazir WP
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

imports:
    - { resource: '@CommonBundle/Resources/config/twig.yaml' }
    # resource: '@CommonBundle/Resources/config/twig.yaml'
##< Nazir WP