<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    Symfony\Bundle\WebServerBundle\WebServerBundle::class => ['dev' => true],
    MiniSystem\MiniCore\TestBundle\TestBundle::class => ['dev' => true, 'test' => true],
    MiniSystem\MiniCore\TstBundle\TstBundle::class => ['dev' => true, 'test' => true],
    MiniSystem\MiniCore\MiniUtilsBundle\MiniUtilsBundle::class => ['all' => true],
    MiniSystem\MiniCore\MiniCommonBundle\MiniCommonBundle::class => ['all' => true],
    MiniSystem\MiniCore\MiniBannerBundle\MiniBannerBundle::class => ['all' => true],
    MiniSystem\MiniCore\MiniUserBundle\MiniUserBundle::class => ['all' => true],
    MiniSystem\MiniCore\MiniAuthBundle\MiniAuthBundle::class => ['all' => true],
    MiniSystem\MiniCore\MiniAdminBundle\MiniAdminBundle::class => ['all' => true],
    MiniSystem\MiniCore\MiniContentBundle\MiniContentBundle::class => ['all' => true],
    MiniSystem\MiniCore\MiniMenuBundle\MiniMenuBundle::class => ['all' => true],
    MiniSystem\MiniCore\MiniEventsBundle\MiniEventsBundle::class => ['all' => true],
    MiniSystem\MiniCore\MiniSocialBundle\MiniSocialBundle::class => ['all' => true],
];
