#index:
#    path: /
#    controller: App\Controller\DefaultController::index

###> Nazir WP
# tst:
#     path: /tst
#     defaults: { _controller: 'MiniSystem\MiniCore\TstBundle\Controller\DefaultController::tst' }

# mini_admin:
#     resource: "@AdminBundle/Controller/"
#     #resource: "@AdminBundle/Resources/config/routing.yaml"
#     type:     annotation
#     prefix:   /

mini_control:
    resource: "@ControlBundle/Controller/"
    #resource: "@ControlBundle/Resources/config/routes.yaml"
    type:     annotation
    prefix:   /

# mini_user:
#     #resource: "@UserBundle/Controller/"
#     resource: "@UserBundle/Resources/config/routes.yaml"
#     #type:     annotation
#     prefix:   /

# mini_menu:
#     resource: "@MenuBundle/Controller/"
#     type:     annotation
#     prefix:   /

# mini_banner:
#     resource: "@BannerBundle/Resources/config/routes.yaml"
#     prefix:   /

# mini_social:
#     resource: "@SocialBundle/Resources/config/routes.yaml"
#     prefix:   /

# mini_calc:
#     resource: "@CalcBundle/Resources/config/routes.yaml"
#     prefix:   /

# mini_bank:
#     resource: "@BankBundle/Resources/config/routes.yaml"
#     prefix:   /

mini_common:
    resource: "@CommonBundle/Resources/config/routes.yaml"
    prefix:   /

# Сторонние бандлы
#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#hwi_oauth_redirect:
#    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
#    prefix:   /connect
#
#hwi_oauth_login:
#    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
#    prefix:   /oauth_login

# Опять свои
# mini_trade:
#     resource: "@TradeBundle/Controller/"
#     #resource: "@TradeBundle/Resources/config/routes.yaml"
#     type:     annotation
#     prefix:   /
# mini_trade_dev:
#     resource: "@TradeDevBundle/Controller/"
#     #resource: "@TradeDevBundle/Resources/config/routes.yaml"
#     type:     annotation
#     prefix:   /

# mini_content:
#     resource: "@ContentBundle/Controller/"
#     #resource: "@ContentBundle/Resources/config/routes.yaml"
#     type:     annotation
#     prefix:   /
###< Nazir WP